# -*- coding: utf-8 -*-
"""Stocks2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4qFpGTrOsejtJ6GD1c2O0g8jlg1mX0e
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

companies_df= pd.read_csv('companies.csv')
companies_stocks_price_df= pd.read_csv('companies_stocks_price.csv')

companies_df.info()

companies_stocks_price_df.info()

companies_stocks_price_df.isnull().sum()

companies_stocks_price_df.duplicated().sum()

companies_stocks_price_df.head()

companies_symbols=[]
for i in companies_df['stock_symbol']:
  companies_symbols.append(i)

companies_symbols

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
companies_stocks_price_df['stock_symbol'] = le.fit_transform(companies_stocks_price_df['stock_symbol'])

companies_stocks_price_df.describe()

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
companies_stocks_price_df[['open','high','low','close','volume']]= scaler.fit_transform(companies_stocks_price_df[['open','high','low','close','volume']])

companies_stocks_price_df.head()

companies_stocks_price_df.drop(['date'],axis=1,inplace=True)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
x_train,x_test,y_train,y_test= train_test_split(companies_stocks_price_df.drop(['close'],axis=1),companies_stocks_price_df['close'],test_size=0.4,random_state=42)

model= LinearRegression()
model.fit(x_train,y_train)

y_pred= model.predict(x_test)
mse= mean_squared_error(y_test,y_pred)
mae= mean_absolute_error(y_test,y_pred)
rmse= np.sqrt(mse)
r2= r2_score(y_test,y_pred)
print(mse,rmse,r2,mae)

y_pred2= model.predict(x_train)
mse= mean_squared_error(y_train,y_pred2)
mae= mean_absolute_error(y_train,y_pred2)
rmse= np.sqrt(mse)
r2= r2_score(y_train,y_pred2)
print(mse,rmse,r2,mae)

